"""empty message

Revision ID: 345f9df1c0ee
Revises: a12dc720ca53
Create Date: 2021-06-23 03:40:28.962784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345f9df1c0ee'
down_revision = 'a12dc720ca53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artist', 'seeking_desciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_desciption', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
