"""empty message

Revision ID: a11b335c4589
Revises: aedf57ef35d3
Create Date: 2021-06-22 21:29:11.066441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11b335c4589'
down_revision = 'aedf57ef35d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    op.drop_column('venue', 'looking_for_Talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_for_Talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'looking_for_talent')
    # ### end Alembic commands ###
