"""empty message

Revision ID: a12dc720ca53
Revises: 7606c80e5d07
Create Date: 2021-06-22 22:02:27.886739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12dc720ca53'
down_revision = '7606c80e5d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_desciption', sa.String(), nullable=True))
    op.drop_column('artist', 'seeking_desc')
    op.drop_column('artist', 'looking_for_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('seeking_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_desciption')
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
