"""empty message

Revision ID: a4b912dbf436
Revises: 4dc0460da628
Create Date: 2021-06-22 11:53:38.081764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b912dbf436'
down_revision = '4dc0460da628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_desc', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('looking_for_Talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_desc')
    op.drop_column('venue', 'looking_for_Talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'seeking_desc')
    op.drop_column('artist', 'looking_for_venues')
    op.drop_column('artist', 'website_link')
    op.drop_table('show')
    # ### end Alembic commands ###
